import React from 'react';
import Header from './header'; // Import the Header component

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Include the Inter font */}
        {/* <style>{inter.getStyleTag()}</style> */}
      </head>
      <body className={inter.className}>
        {/* Include the Header component */}
        <Header />
        {/* Render children */}
        {children}
      </body>
    </html>
  );
}
